sudo: true
language: node_js
node_js:
  - 10
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t manishsingh10895/docker-react .

script:
  - docker run manishsingh10895/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-879095799300"
  bucket_path: "docker-frontend"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"